server:
   port: 8384
   
spring:
   application:
      name: monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8380/eureka/
      
security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}