server:
   port: 8380
   
spring:
   application:
      name: registry

eureka:
   instance:
      hostname: localhost
      #表示将自己的IP注册到Eureka Server
      prefer-id-address: true
   client:
      #是否向服务注册中心注册自己
      registerWithEureka: false
      #是否检索服务
      fetchRegistry: false
      #服务注册中心的配置内容，指定服务注册中心的位置
      service-url:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      