server:
   port: 8180

spring:
   application:
      name: config-server
      
spring:
   cloud:
      server:
         git:
            uri:
            searchPaths: config-repo
            username: 
            password: 
         lable: master
         
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8888/eureka/
         
  
   