server:
   port: 8381
      
spring:
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/lxlbz3696096/spring-cloud
               searchPaths: config-repo
               username: lxlbz3696096
               password: liuxulbz3696096
         label: master
         
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8380/eureka/
         
  
   